name: publish to nuget
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing a /
jobs:
  publish:
    name: build, pack & publish to nuget.org
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Create Build Directory
        run: mkdir _build

      - name: Restore Packages
        run: nuget restore FemDesign.Core/FemDesign.Core.csproj

      - name: Build Solution
        run: |
          dotnet build .\FemDesign.Core\FemDesign.Core.csproj -c Release

      - name: Pack nuget
        run: |
          nuget pack .\FemDesign.Core\
      
      - name: Publish nuget
        run: |
          nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{secrets.NUGET_API_KEY}}
